from abc import ABC, abstractmethod
from typing import List, Optional
from app.core.config import settings
from app.observability.logging import logger

class LLMClient(ABC):
    @abstractmethod
    async def generate_answer(self, query: str, context: List[str]) -> str:
        pass

class MockLLMClient(LLMClient):
    """
    Deterministic fallback or dev-mode LLM.
    Just summarizes that it found X documents.
    """
    async def generate_answer(self, query: str, context: List[str]) -> str:
        if not context:
            return "I could not find any relevant information in the knowledge base."
        
        # Simple deterministic summary for testing without API keys
        return (
            f"Based on the {len(context)} retrieved documents, here is the information:\n\n"
            f"{' ... '.join([c[:200] for c in context])}...\n\n"
            "(Generated by MockLLM - configuration required for real AI)"
        )

class OpenAIClient(LLMClient):
    def __init__(self):
        try:
            from openai import AsyncOpenAI
            if not settings.OPENAI_API_KEY:
                raise ValueError("OPENAI_API_KEY not set")
            self.client = AsyncOpenAI(
                api_key=settings.OPENAI_API_KEY,
                base_url=settings.OPENAI_BASE_URL
            )
            # OpenRouter often uses different model names, e.g. "openai/gpt-3.5-turbo" or "meta-llama/llama-3-8b-instruct"
            # Defaulting to a cheap one for now, or keeping gpt-3.5-turbo if supported (OpenRouter usually maps it)
            self.model = settings.LLM_MODEL_NAME 
        except ImportError:
            logger.error("openai library not installed")
            raise

    async def generate_answer(self, query: str, context: List[str]) -> str:
        system_prompt = (
            "You are an enterprise knowledge assistant. "
            "Answer strictly based on the provided context. "
            "If the answer is not in the context, say you don't know."
        )
        context_str = "\n---\n".join(context)
        user_content = f"Context:\n{context_str}\n\nQuestion: {query}"
        
        try:
            response = await self.client.chat.completions.create(
                model=self.model,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_content}
                ],
                temperature=0.0
            )
            return response.choices[0].message.content
        except Exception as e:
            logger.error(f"LLM generation failed: {e}")
            return "Error generating response from AI provider."

def get_llm_client() -> LLMClient:
    # Logic to switch providers
    if settings.OPENAI_API_KEY:
         return OpenAIClient()
    return MockLLMClient()
